### ISSUE TITLE
Overflow error in model zoo example

### ISSUE THREAD

**Issue by ljschumacher** [FluxML/model-zoo#163] opened 2019-09-06 15:20 UTC
I'm running the neural SDE example https://github.com/FluxML/model-zoo/blob/master/other/diffeq/neural_sde.jl

and on the last line `Flux.train!(loss_n_sde, ps, data, opt, cb = cb)` I'm getting a `StackOverflowError:` after a few training steps.

I'm running Mac OS X and here's output of my `Pkg.status(`
`Status `~/.juliapro/JuliaPro_v1.2.0-1/environments/v1.2/Project.toml`
  [c52e3926] Atom v0.9.1
  [aae7a2af] DiffEqFlux v0.6.1
  [0c46a032] DifferentialEquations v6.6.0
  [587475ba] Flux v0.8.3
  [7073ff75] IJulia v1.19.0
  [e5e0dc1b] Juno v0.7.1
  [91a5bcdd] Plots v0.26.2`

**Comment by joostveenema** [comment] 2021-01-27 08:34
duplicate of https://github.com/FluxML/model-zoo/issues/182

**Closed** 2021-01-27 08:36 UTC
